### ISSUE TITLE
Learning Path / Roadmap to be Xamarin (iOS | Android | Cross Platform) Developer

### ISSUE THREAD

**Issue by dionnyprensa** [xamarinuniverse/XamarinUniversalLibrary#16]
**It's necessary have a path to travel with the correct information and exact knowledge.**
*Don't loss the time.*

It could be a list of courses (maybe divided by levels) with a specific order.
- 1: Entry level
- 2 - 4: Beginner
- 5 - 7: Average level
- 8 - 10: Advanced

Example:
1. "What is Xamarin?" - A Post, Video or Course
2. "How does Xamarin work?" - A Post, Video or Course
3. "Hello World in Xamarin" - A Post, Video or Course

**Comment by luismts** [comment]
@dionnyprensa you can create the Roadmap Section in the library following the structure in order that others can just add the information. What do you think?

**Comment by dionnyprensa** [comment]
I really have no idea of a roadmap for Xamarin.
Like me, there are many people who would like to start and do not know where to do it or find bad information and leave Xamarin.

Later I'll see if I only create the section.

**Comment by luismts** [comment]
No, no, no. You are getting confused @dionnyprensa . Just create the section like the table, the contributing guideline, etc. With this other can give us their contribution easily. 

More info [here](https://github.com/xamarinuniverse/XamarinUniversalLibrary#want-to-add-a-new-section-or-sub-section).

**Comment by yauhenipakala** [comment]
Hi everyone!

Some time ago I created the initial version of this roadmap (learning-path):
https://github.com/it-shark-pro/mobile-xamarin/blob/master/learning-path.md

@dionnyprensa  Could you please send your feedback about that?
@luismts I can migrate learning-path to XUL too.

**Comment by dionnyprensa** [comment]
It's great. @wcoder 

That could also have Pluralsight, Udemy, Coursera courses.

**Comment by luismts** [comment]
@wcoder excellent. The roadmap is going to have an author with a link with his professional social network or Github. I really like the idea!
