### ISSUE TITLE
404 in articles/under-the-hood

### ISSUE THREAD

**Issue by dev-aritra** [xamarinuniverse/XamarinUniversalLibrary#32]
https://github.com/xamarinuniverse/XamarinUniversalLibrary/blob/master/src/articles/article-topics/Under-the-hood.md

This URL is currently hitting a 404

**Comment by yauhenipakala** [comment]
@dev-aritra thanks for the report!

Fixed, right url: https://github.com/xamarinuniverse/XamarinUniversalLibrary/blob/master/src/articles/article-topics/Under-the-Hood.md
